[flaskers]
flask1 ansible_host=34.224.27.110 ansible_user=ubuntu ansible_ssh_private_key_file=/Users/geraldoti/Downloads/practice.pem
flask2 ansible_host=32.199.177.239 ansible_user=ubuntu ansible_ssh_private_key_file=/Users/geraldoti/Downloads/practice.pem
